name: Test Docker image action
on:
  push:
  
  pull_request:
    types: [opened, synchronize, reopened]
    
  workflow_dispatch:

jobs:
  test-from-source:
    runs-on: ubuntu-latest
    steps:
      - uses: kyanny/hello-world-docker-action@v0.1.1

  test-from-image:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://ghcr.io/kyanny/hello-world-docker-action:0.1.1
